# MySQL Datasource Configuration
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#AWS S3 Bucket
aws.accessKeyId=${S3_BUCKET_ACCESS_KEY_ID}
aws.secretKey=${S3_BUCKET_SECRET_KEY}
aws.region=${S3_BUCKET_REGION}
aws.s3.bucket=${S3_BUCKET_NAME}

# Razorpay Configuration
razorpay.key.id=rzp_test_RdJgAzLTPMFmdN
razorpay.key.secret=aWjuCepGEZBIqcnP4pgRwe2X
#razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_YOUR_KEY_ID}
#razorpay.key.secret=${RAZORPAY_KEY_SECRET:YOUR_SECRET_KEY}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET:YOUR_WEBHOOK_SECRET}

# AWS SES Configuration
aws.ses.region=ap-south-1

aws.ses.from.name=PropertyDealz Notifications

# AWS SNS Configuration
aws.ses.access-key=AKIA2D2F4LAGLLC3YQ751118888111
aws.ses.secret-key=0lcJfLQJkWXZBNOqGVotaeydX9ZSN/TKMf3SYynn11111
aws.sns.region=ap-south-1
aws.sns.sender-id=PROPDEALS
aws.ses.sender-email=nsrinivas.0975@outlook.com
aws.ses.from.email=nsrinivas.0975@outlook.com

# Meta WhatsApp Cloud API Configuration
whatsapp.api.url=https://graph.facebook.com/v18.0
whatsapp.phone.number.id=904144246111842
whatsapp.access.token=EAAcs6ZCNdAIABQD4Fkt3aZCvWYeLN9AQOikcRlnVSkjsHEPGohl5CoHfdNNU5Nf7aREslVrYvTcbtZAoTkDdYZAn2jUQoXpZCsvBG7hvedzPGJbrA9SqAvRXkcbQklvUSApEfWd81FZAgB0qWzJat4f8UuPMkZAhJ7EI62Enr4LEbCc4yHhBdyNW4gS1ZBtikDwm3fRyCd3PCqxAShZBUwfTZA5o9k0wsbxZBSjnaFDCQJHIGMz7iZA9au4piT92Dglx84d7dYVpUxUumaSV5Aan4cCAfAZDZD
whatsapp.business.account.id=819711817700338

# Notification Settings
notification.enabled=true
notification.admins.emails=nsrinivas.0975@outlook.com,nsrinivas.0975@gmail.com,rakeshrachapudi04@gmail.com
notification.admins.phones=7730051329,6309806984,7730051329,8801706060

# Frontend URL
frontend.base.url=${FRONTEND_BASE_URL:https://propertydealz.in}

# Enable feature (production)
property.tracking.enabled=true


# Enable scheduling for subscription expiry
spring.task.scheduling.enabled=true


# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS Configuration - Support both ports
#spring.web.cors.allowed-origins=${FRONTEND_BASE_URL}
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=*
#spring.web.cors.allow-credentials=true

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata

# Logging
logging.level.root=INFO
logging.level.com.example.realestate=DEBUG
